### PR TITLE
Better explain installation errors

### PR DESCRIPTION
**Pull request by charlieegan3**
This gives more helpful errors like this:

```
$ go run main.go operator installations status --kubeconfig=dist/config.yaml
no installations.operator.jetstack.io CRD found in cluster "https://127.0.0.1:52378/", have you run 'jsctl operator deploy'?
exit status 1

$ go run main.go operator deploy --kubeconfig=dist/config.yaml  --auto-registry-credentials

$ go run main.go operator installations status --kubeconfig=dist/config.yaml
no installations.operator.jetstack.io resources found in cluster "https://127.0.0.1:52378/", have you run 'jsctl operator installations apply'?
exit status 1

$ go run main.go operator installations apply --kubeconfig=dist/config.yaml

$ go run main.go operator installations status --kubeconfig=dist/config.yaml
COMPONENT          READY    MESSAGE
approver-policy    false    DeploymentReplicaMismatch: expected replicas 2, found ready replicas 0
manifests          true

```

### CODE REVIEW

**Comment by irbekrm** [comment]
I think it makes sense to ensure that the namespace exists for scenarios where perhaps js-agent was already existing in cluster deployed by other means, but I think there should not be a need for a flag as it's confusing for users (when should they set it to false?). Should we instead just have a check for whether the namespace exists and create it if it doesn't?

> https://github.com/jetstack/jsctl/commit/5a033fb1e0dafaced2cfdf75f858349c7eefbc26 is intended to make it clear why a operation relating to the installation of the operator has failed.

Is this the same as #29 ?

**Comment by charlieegan3** [comment]
> Is this the same as https://github.com/jetstack/jsctl/pull/29 ?

Oops, looks like I left the commit on here too. I'll merge them both into this one.

**Comment by charlieegan3** [comment]
>when should they set it to false?

I left the flag in so that users using the stdout applier had an option to control this behaviour too. Perhaps that's not required?

**Comment by charlieegan3** [comment]
>yeah it's a good point about stdout. I'd be more tempted then to leave it as is- the namespace gets created with the agent if jsctl clusters connect is run and we don't, at the moment, have much support for migrating existing installations, so we might as well assume a clean start for now?

Ok, I can take it out for now.

**Review by irbekrm — APPROVED** [review]
Nice, tested by hand and all works as expected now 👍🏼 

I think the messages will be helpful!

/lgtm

**Pull request merged**
